//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromptPlusLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PromptPlusResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PromptPlusResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PromptPlusLibrary.Resources.PromptPlusResources", typeof(PromptPlusResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or press any other key to end.
        /// </summary>
        internal static string AnyKey {
            get {
                return ResourceManager.GetString("AnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string CanceledKey {
            get {
                return ResourceManager.GetString("CanceledKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+B:Moves cursor backward one word.
        /// </summary>
        internal static string Emac_alt_b {
            get {
                return ResourceManager.GetString("Emac_alt_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+C:Capitalizes character under the cursor and moves to the end the word.
        /// </summary>
        internal static string Emac_alt_c {
            get {
                return ResourceManager.GetString("Emac_alt_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+D:Clear word after cursor.
        /// </summary>
        internal static string Emac_alt_d {
            get {
                return ResourceManager.GetString("Emac_alt_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+F:Moves cursor forward one word.
        /// </summary>
        internal static string Emac_alt_f {
            get {
                return ResourceManager.GetString("Emac_alt_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+L:Lowercase from cursor to end of word.
        /// </summary>
        internal static string Emac_alt_l {
            get {
                return ResourceManager.GetString("Emac_alt_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+U:Upper case from the cursor to the end the word..
        /// </summary>
        internal static string Emac_alt_u {
            get {
                return ResourceManager.GetString("Emac_alt_u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+A:Moves the cursor to the line start (equivalent to the home key).
        /// </summary>
        internal static string Emac_ctrl_a {
            get {
                return ResourceManager.GetString("Emac_ctrl_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+B:Moves the cursor back one character (equivalent to the left arrow key).
        /// </summary>
        internal static string Emac_ctrl_b {
            get {
                return ResourceManager.GetString("Emac_ctrl_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+D:Delete the current character (equivalent to the delete key).
        /// </summary>
        internal static string Emac_ctrl_d {
            get {
                return ResourceManager.GetString("Emac_ctrl_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+E:Moves cursor to the line end (equivalent to the end key).
        /// </summary>
        internal static string Emac_ctrl_e {
            get {
                return ResourceManager.GetString("Emac_ctrl_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+F:Moves the cursor forward one character (equivalent to the right arrow key).
        /// </summary>
        internal static string Emac_ctrl_f {
            get {
                return ResourceManager.GetString("Emac_ctrl_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+H:Deletes the previous character (equivalent to the backspace key).
        /// </summary>
        internal static string Emac_ctrl_h {
            get {
                return ResourceManager.GetString("Emac_ctrl_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+K:Clears the line after cursor.
        /// </summary>
        internal static string Emac_ctrl_k {
            get {
                return ResourceManager.GetString("Emac_ctrl_k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+L:Clears all content.
        /// </summary>
        internal static string Emac_ctrl_l {
            get {
                return ResourceManager.GetString("Emac_ctrl_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+T:Transpose the previous two characters.
        /// </summary>
        internal static string Emac_ctrl_t {
            get {
                return ResourceManager.GetString("Emac_ctrl_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+U:Clears the line before cursor.
        /// </summary>
        internal static string Emac_ctrl_u {
            get {
                return ResourceManager.GetString("Emac_ctrl_u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+W:Clear the word before cursor.
        /// </summary>
        internal static string Emac_ctrl_w {
            get {
                return ResourceManager.GetString("Emac_ctrl_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert:Toggle input replacement mode (default is insert mode).
        /// </summary>
        internal static string Emac_Insert {
            get {
                return ResourceManager.GetString("Emac_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry history.
        /// </summary>
        internal static string EntryHistory {
            get {
                return ResourceManager.GetString("EntryHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice options.
        /// </summary>
        internal static string EntryOptions {
            get {
                return ResourceManager.GetString("EntryOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at AutoComplete Service.
        /// </summary>
        internal static string ErrorAutoCompleteService {
            get {
                return ResourceManager.GetString("ErrorAutoCompleteService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder : {0}.
        /// </summary>
        internal static string FileInfoFolder {
            get {
                return ResourceManager.GetString("FileInfoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder.
        /// </summary>
        internal static string FileInfoRoot {
            get {
                return ResourceManager.GetString("FileInfoRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered.
        /// </summary>
        internal static string Filtered {
            get {
                return ResourceManager.GetString("Filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty history for input data.
        /// </summary>
        internal static string HistoryNotFound {
            get {
                return ResourceManager.GetString("HistoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter:Finish.
        /// </summary>
        internal static string InputFinishEnter {
            get {
                return ResourceManager.GetString("InputFinishEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter:Apply filter.
        /// </summary>
        internal static string InputFinishFilter {
            get {
                return ResourceManager.GetString("InputFinishFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Key: {0}.
        /// </summary>
        internal static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unreported entries..
        /// </summary>
        internal static string MaskeditInputPending {
            get {
                return ResourceManager.GetString("MaskeditInputPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries with invalid values.
        /// </summary>
        internal static string MaskEditInvalidInput {
            get {
                return ResourceManager.GetString("MaskEditInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any char  (A-Z,a-z,0-9).
        /// </summary>
        internal static string MaskEditPosAnyChar {
            get {
                return ResourceManager.GetString("MaskEditPosAnyChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant ({0}).
        /// </summary>
        internal static string MaskEditPosConstant {
            get {
                return ResourceManager.GetString("MaskEditPosConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Symbol.
        /// </summary>
        internal static string MaskEditPosCurrencySymbol {
            get {
                return ResourceManager.GetString("MaskEditPosCurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}Only({2}).
        /// </summary>
        internal static string MaskEditPosCustom {
            get {
                return ResourceManager.GetString("MaskEditPosCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date separator.
        /// </summary>
        internal static string MaskEditPosDateSep {
            get {
                return ResourceManager.GetString("MaskEditPosDateSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day (0-9).
        /// </summary>
        internal static string MaskEditPosDay {
            get {
                return ResourceManager.GetString("MaskEditPosDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal separator.
        /// </summary>
        internal static string MaskEditPosDecSep {
            get {
                return ResourceManager.GetString("MaskEditPosDecSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group separator.
        /// </summary>
        internal static string MaskEditPosGrpSep {
            get {
                return ResourceManager.GetString("MaskEditPosGrpSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour (0-9).
        /// </summary>
        internal static string MaskEditPosHour {
            get {
                return ResourceManager.GetString("MaskEditPosHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter (A-Z,a-z).
        /// </summary>
        internal static string MaskEditPosLetter {
            get {
                return ResourceManager.GetString("MaskEditPosLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letra  (a-z).
        /// </summary>
        internal static string MaskEditPosLetterLower {
            get {
                return ResourceManager.GetString("MaskEditPosLetterLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter (A-Z).
        /// </summary>
        internal static string MaskEditPosLetterUpper {
            get {
                return ResourceManager.GetString("MaskEditPosLetterUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute (0-9).
        /// </summary>
        internal static string MaskEditPosMinute {
            get {
                return ResourceManager.GetString("MaskEditPosMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month (0-9).
        /// </summary>
        internal static string MaskEditPosMonth {
            get {
                return ResourceManager.GetString("MaskEditPosMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric (0-9).
        /// </summary>
        internal static string MaskEditPosNumeric {
            get {
                return ResourceManager.GetString("MaskEditPosNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second (0-9).
        /// </summary>
        internal static string MaskEditPosSecond {
            get {
                return ResourceManager.GetString("MaskEditPosSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal +-.
        /// </summary>
        internal static string MaskEditPosSing {
            get {
                return ResourceManager.GetString("MaskEditPosSing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string MaskEditPosSpace {
            get {
                return ResourceManager.GetString("MaskEditPosSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time seprator.
        /// </summary>
        internal static string MaskEditPosTimeSep {
            get {
                return ResourceManager.GetString("MaskEditPosTimeSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year (0-9).
        /// </summary>
        internal static string MaskEditPosYear {
            get {
                return ResourceManager.GetString("MaskEditPosYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right:Change day.
        /// </summary>
        internal static string MoveDays {
            get {
                return ResourceManager.GetString("MoveDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up/Down:Change day with same day of week.
        /// </summary>
        internal static string MoveDayWeek {
            get {
                return ResourceManager.GetString("MoveDayWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab/Shift Tab:Change Month.
        /// </summary>
        internal static string MoveMonth {
            get {
                return ResourceManager.GetString("MoveMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home:Today.
        /// </summary>
        internal static string MoveToday {
            get {
                return ResourceManager.GetString("MoveToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PgUp/PgDown:Change year.
        /// </summary>
        internal static string MoveYear {
            get {
                return ResourceManager.GetString("MoveYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space:Check/Uncheck.
        /// </summary>
        internal static string MultiSelectCheck {
            get {
                return ResourceManager.GetString("MultiSelectCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum item selection({0}) has been exceeded.
        /// </summary>
        internal static string MultiSelectMaxSelection {
            get {
                return ResourceManager.GetString("MultiSelectMaxSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum selection of {0} items is required.
        /// </summary>
        internal static string MultiSelectMinSelection {
            get {
                return ResourceManager.GetString("MultiSelectMinSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string NoChar {
            get {
                return ResourceManager.GetString("NoChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path : .
        /// </summary>
        internal static string NodePath {
            get {
                return ResourceManager.GetString("NodePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are marked items, cannot be collapsed.
        /// </summary>
        internal static string NotCollapse {
            get {
                return ResourceManager.GetString("NotCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty notes  for input data.
        /// </summary>
        internal static string NoteNotFound {
            get {
                return ResourceManager.GetString("NoteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OffValue {
            get {
                return ResourceManager.GetString("OffValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string OnValue {
            get {
                return ResourceManager.GetString("OnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest value.
        /// </summary>
        internal static string OrderHighest {
            get {
                return ResourceManager.GetString("OrderHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label ascending.
        /// </summary>
        internal static string OrderLabelAsc {
            get {
                return ResourceManager.GetString("OrderLabelAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label descending.
        /// </summary>
        internal static string OrderLabelDec {
            get {
                return ResourceManager.GetString("OrderLabelDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smallest value.
        /// </summary>
        internal static string OrderSmallest {
            get {
                return ResourceManager.GetString("OrderSmallest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string OrderStandard {
            get {
                return ResourceManager.GetString("OrderStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying: {1}/{2} pages of {0} items..
        /// </summary>
        internal static string PaginationTemplate {
            get {
                return ResourceManager.GetString("PaginationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected item does not meet the criteria.
        /// </summary>
        internal static string PredicateSelectInvalid {
            get {
                return ResourceManager.GetString("PredicateSelectInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressed key.
        /// </summary>
        internal static string PressedKey {
            get {
                return ResourceManager.GetString("PressedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filter :.
        /// </summary>
        internal static string SearchFilter {
            get {
                return ResourceManager.GetString("SearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item disabled.
        /// </summary>
        internal static string SelectionDisabled {
            get {
                return ResourceManager.GetString("SelectionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing notes of the day {0}.
        /// </summary>
        internal static string ShowingCalendarNotes {
            get {
                return ResourceManager.GetString("ShowingCalendarNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right:Short change, Tab/Shift+Tab:Larger change.
        /// </summary>
        internal static string SliderNumberLeftRightKeyNavigator {
            get {
                return ResourceManager.GetString("SliderNumberLeftRightKeyNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up/Down:Short change, Tab/Shift+Tab:Larger change.
        /// </summary>
        internal static string SliderNumberUpDownKeyNavigator {
            get {
                return ResourceManager.GetString("SliderNumberUpDownKeyNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+Space = Space for filter.
        /// </summary>
        internal static string SpaceMultSelect {
            get {
                return ResourceManager.GetString("SpaceMultSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right:Change.
        /// </summary>
        internal static string SwitchKeyNavigator {
            get {
                return ResourceManager.GetString("SwitchKeyNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows: {0}.
        /// </summary>
        internal static string TableAnswerMultiRow {
            get {
                return ResourceManager.GetString("TableAnswerMultiRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row: {0}.
        /// </summary>
        internal static string TableAnswerRow {
            get {
                return ResourceManager.GetString("TableAnswerRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Ctrl+Left/Right:Move column.
        /// </summary>
        internal static string TableMoveCols {
            get {
                return ResourceManager.GetString("TableMoveCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing {0} task(s).
        /// </summary>
        internal static string TaksRunning {
            get {
                return ResourceManager.GetString("TaksRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} completed, {1} Error, {2} canceled.
        /// </summary>
        internal static string TaskFiniched {
            get {
                return ResourceManager.GetString("TaskFiniched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task{0}.
        /// </summary>
        internal static string TaskSeqName {
            get {
                return ResourceManager.GetString("TaskSeqName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:To cancel.
        /// </summary>
        internal static string TooltipCancelEsc {
            get {
                return ResourceManager.GetString("TooltipCancelEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up/Down/PgUp/PgDown:Move, Enter:Finish.
        /// </summary>
        internal static string TooltipChart {
            get {
                return ResourceManager.GetString("TooltipChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Switch view legend.
        /// </summary>
        internal static string TooltipChartSwitchLegend {
            get {
                return ResourceManager.GetString("TooltipChartSwitchLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Switch order view.
        /// </summary>
        internal static string TooltipChartSwitchOrder {
            get {
                return ResourceManager.GetString("TooltipChartSwitchOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Toggle Chart type.
        /// </summary>
        internal static string TooltipChartSwitchType {
            get {
                return ResourceManager.GetString("TooltipChartSwitchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seleted..
        /// </summary>
        internal static string TooltipCountCheck {
            get {
                return ResourceManager.GetString("TooltipCountCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+:Expand All.
        /// </summary>
        internal static string TooltipExpandAllPress {
            get {
                return ResourceManager.GetString("TooltipExpandAllPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Toggle filter mode.
        /// </summary>
        internal static string TooltipFilterMode {
            get {
                return ResourceManager.GetString("TooltipFilterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Del:Clear historic.
        /// </summary>
        internal static string TooltipHistoryClear {
            get {
                return ResourceManager.GetString("TooltipHistoryClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc:Cancel historic.
        /// </summary>
        internal static string TooltipHistoryEsc {
            get {
                return ResourceManager.GetString("TooltipHistoryEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Show Historic.
        /// </summary>
        internal static string TooltipHistoryKey {
            get {
                return ResourceManager.GetString("TooltipHistoryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Show Historic(Min. {1} chars).
        /// </summary>
        internal static string TooltipHistoryShow {
            get {
                return ResourceManager.GetString("TooltipHistoryShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home:Previus level, End : Last Item of level.
        /// </summary>
        internal static string TooltipLevelHomeEnd {
            get {
                return ResourceManager.GetString("TooltipLevelHomeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordination: {0}.
        /// </summary>
        internal static string TooltipOrder {
            get {
                return ResourceManager.GetString("TooltipOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up/Down/PgUp/PgDown:Move Selector.
        /// </summary>
        internal static string TooltipPages {
            get {
                return ResourceManager.GetString("TooltipPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Toggle Mark All.
        /// </summary>
        internal static string TooltipSelectAll {
            get {
                return ResourceManager.GetString("TooltipSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Show/Hide tooltips.
        /// </summary>
        internal static string TooltipShowHide {
            get {
                return ResourceManager.GetString("TooltipShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc:Cancel suggestion.
        /// </summary>
        internal static string TooltipSuggestionEsc {
            get {
                return ResourceManager.GetString("TooltipSuggestionEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab/Shift Tab:Suggestions.
        /// </summary>
        internal static string TooltipSuggestionToggle {
            get {
                return ResourceManager.GetString("TooltipSuggestionToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Toggle tooltips.
        /// </summary>
        internal static string TooltipToggle {
            get {
                return ResourceManager.GetString("TooltipToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +/-:Expand/Collapse.
        /// </summary>
        internal static string TooltipToggleExpandPress {
            get {
                return ResourceManager.GetString("TooltipToggleExpandPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Toggle Notes.
        /// </summary>
        internal static string TooltipToggleNotes {
            get {
                return ResourceManager.GetString("TooltipToggleNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Switch view password.
        /// </summary>
        internal static string TooltipViewPassword {
            get {
                return ResourceManager.GetString("TooltipViewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer:.
        /// </summary>
        internal static string TooltipWaitTimer {
            get {
                return ResourceManager.GetString("TooltipWaitTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloading....
        /// </summary>
        internal static string Unloading {
            get {
                return ResourceManager.GetString("Unloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid key: {0}.
        /// </summary>
        internal static string ValidAnyKey {
            get {
                return ResourceManager.GetString("ValidAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value!.
        /// </summary>
        internal static string ValidateInvalid {
            get {
                return ResourceManager.GetString("ValidateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too long. Max({0}).
        /// </summary>
        internal static string ValidateMaxLength {
            get {
                return ResourceManager.GetString("ValidateMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too short. Min({0}).
        /// </summary>
        internal static string ValidateMinLength {
            get {
                return ResourceManager.GetString("ValidateMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not match pattern.
        /// </summary>
        internal static string ValidateNoMatchRegex {
            get {
                return ResourceManager.GetString("ValidateNoMatchRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Value!.
        /// </summary>
        internal static string ValidateRequired {
            get {
                return ResourceManager.GetString("ValidateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string YesChar {
            get {
                return ResourceManager.GetString("YesChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
