//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromptPlusLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PromptPlusResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PromptPlusResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PromptPlusLibrary.Resources.PromptPlusResources", typeof(PromptPlusResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string CanceledKey {
            get {
                return ResourceManager.GetString("CanceledKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col.
        /// </summary>
        internal static string Col_Info {
            get {
                return ResourceManager.GetString("Col_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+B:Moves cursor backward one word.
        /// </summary>
        internal static string Emac_alt_b {
            get {
                return ResourceManager.GetString("Emac_alt_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+C:Capitalizes character under the cursor and moves to the end the word.
        /// </summary>
        internal static string Emac_alt_c {
            get {
                return ResourceManager.GetString("Emac_alt_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+D:Clear word after cursor.
        /// </summary>
        internal static string Emac_alt_d {
            get {
                return ResourceManager.GetString("Emac_alt_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+F:Moves cursor forward one word.
        /// </summary>
        internal static string Emac_alt_f {
            get {
                return ResourceManager.GetString("Emac_alt_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+L:Lowercase from cursor to end of word.
        /// </summary>
        internal static string Emac_alt_l {
            get {
                return ResourceManager.GetString("Emac_alt_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+U:Upper case from the cursor to the end the word..
        /// </summary>
        internal static string Emac_alt_u {
            get {
                return ResourceManager.GetString("Emac_alt_u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+A:Moves the cursor to the line start (equivalent to the home key).
        /// </summary>
        internal static string Emac_ctrl_a {
            get {
                return ResourceManager.GetString("Emac_ctrl_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+B:Moves the cursor back one character (equivalent to the left arrow key).
        /// </summary>
        internal static string Emac_ctrl_b {
            get {
                return ResourceManager.GetString("Emac_ctrl_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+D:Delete the current character (equivalent to the delete key).
        /// </summary>
        internal static string Emac_ctrl_d {
            get {
                return ResourceManager.GetString("Emac_ctrl_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+E:Moves cursor to the line end (equivalent to the end key).
        /// </summary>
        internal static string Emac_ctrl_e {
            get {
                return ResourceManager.GetString("Emac_ctrl_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+F:Moves the cursor forward one character (equivalent to the right arrow key).
        /// </summary>
        internal static string Emac_ctrl_f {
            get {
                return ResourceManager.GetString("Emac_ctrl_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+H:Deletes the previous character (equivalent to the backspace key).
        /// </summary>
        internal static string Emac_ctrl_h {
            get {
                return ResourceManager.GetString("Emac_ctrl_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+K:Clears the line after cursor.
        /// </summary>
        internal static string Emac_ctrl_k {
            get {
                return ResourceManager.GetString("Emac_ctrl_k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+L:Clears all content.
        /// </summary>
        internal static string Emac_ctrl_l {
            get {
                return ResourceManager.GetString("Emac_ctrl_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+T:Transpose the previous two characters.
        /// </summary>
        internal static string Emac_ctrl_t {
            get {
                return ResourceManager.GetString("Emac_ctrl_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+U:Clears the line before cursor.
        /// </summary>
        internal static string Emac_ctrl_u {
            get {
                return ResourceManager.GetString("Emac_ctrl_u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+W:Clear the word before cursor.
        /// </summary>
        internal static string Emac_ctrl_w {
            get {
                return ResourceManager.GetString("Emac_ctrl_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert:Toggle input replacement mode (default is insert mode).
        /// </summary>
        internal static string Emac_Insert {
            get {
                return ResourceManager.GetString("Emac_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry histories.
        /// </summary>
        internal static string EntryHistory {
            get {
                return ResourceManager.GetString("EntryHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Suggestions.
        /// </summary>
        internal static string EntrySuggestion {
            get {
                return ResourceManager.GetString("EntrySuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty history for input data.
        /// </summary>
        internal static string HistoryNotFound {
            get {
                return ResourceManager.GetString("HistoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter:Finish.
        /// </summary>
        internal static string InputFinishEnter {
            get {
                return ResourceManager.GetString("InputFinishEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date selected!.
        /// </summary>
        internal static string InvalidDateSelect {
            get {
                return ResourceManager.GetString("InvalidDateSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unreported entries..
        /// </summary>
        internal static string MaskeditInputPending {
            get {
                return ResourceManager.GetString("MaskeditInputPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries with invalid values.
        /// </summary>
        internal static string MaskEditInvalidInput {
            get {
                return ResourceManager.GetString("MaskEditInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any char (A-Z,a-z,0-9).
        /// </summary>
        internal static string MaskEditPosAnyChar {
            get {
                return ResourceManager.GetString("MaskEditPosAnyChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant ({0}).
        /// </summary>
        internal static string MaskEditPosConstant {
            get {
                return ResourceManager.GetString("MaskEditPosConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Symbol.
        /// </summary>
        internal static string MaskEditPosCurrencySymbol {
            get {
                return ResourceManager.GetString("MaskEditPosCurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}Only({2}).
        /// </summary>
        internal static string MaskEditPosCustom {
            get {
                return ResourceManager.GetString("MaskEditPosCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date separator.
        /// </summary>
        internal static string MaskEditPosDateSep {
            get {
                return ResourceManager.GetString("MaskEditPosDateSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day (0-9).
        /// </summary>
        internal static string MaskEditPosDay {
            get {
                return ResourceManager.GetString("MaskEditPosDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal separator.
        /// </summary>
        internal static string MaskEditPosDecSep {
            get {
                return ResourceManager.GetString("MaskEditPosDecSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group separator.
        /// </summary>
        internal static string MaskEditPosGrpSep {
            get {
                return ResourceManager.GetString("MaskEditPosGrpSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour (0-9).
        /// </summary>
        internal static string MaskEditPosHour {
            get {
                return ResourceManager.GetString("MaskEditPosHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter (A-Z,a-z).
        /// </summary>
        internal static string MaskEditPosLetter {
            get {
                return ResourceManager.GetString("MaskEditPosLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter (a-z).
        /// </summary>
        internal static string MaskEditPosLetterLower {
            get {
                return ResourceManager.GetString("MaskEditPosLetterLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter (A-Z).
        /// </summary>
        internal static string MaskEditPosLetterUpper {
            get {
                return ResourceManager.GetString("MaskEditPosLetterUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute (0-9).
        /// </summary>
        internal static string MaskEditPosMinute {
            get {
                return ResourceManager.GetString("MaskEditPosMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month (0-9).
        /// </summary>
        internal static string MaskEditPosMonth {
            get {
                return ResourceManager.GetString("MaskEditPosMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric (0-9).
        /// </summary>
        internal static string MaskEditPosNumeric {
            get {
                return ResourceManager.GetString("MaskEditPosNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second (0-9).
        /// </summary>
        internal static string MaskEditPosSecond {
            get {
                return ResourceManager.GetString("MaskEditPosSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal +-.
        /// </summary>
        internal static string MaskEditPosSing {
            get {
                return ResourceManager.GetString("MaskEditPosSing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string MaskEditPosSpace {
            get {
                return ResourceManager.GetString("MaskEditPosSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time seprator.
        /// </summary>
        internal static string MaskEditPosTimeSep {
            get {
                return ResourceManager.GetString("MaskEditPosTimeSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year (0-9).
        /// </summary>
        internal static string MaskEditPosYear {
            get {
                return ResourceManager.GetString("MaskEditPosYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right:Change day.
        /// </summary>
        internal static string MoveDays {
            get {
                return ResourceManager.GetString("MoveDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up/Down:Change day with same day of week.
        /// </summary>
        internal static string MoveDayWeek {
            get {
                return ResourceManager.GetString("MoveDayWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab/Shift Tab:Change Month.
        /// </summary>
        internal static string MoveMonth {
            get {
                return ResourceManager.GetString("MoveMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home:Today.
        /// </summary>
        internal static string MoveToday {
            get {
                return ResourceManager.GetString("MoveToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PgUp/PgDown:Change year.
        /// </summary>
        internal static string MoveYear {
            get {
                return ResourceManager.GetString("MoveYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading PromptPlus configuration..
        /// </summary>
        internal static string MsgErrorPromptPlusConfig {
            get {
                return ResourceManager.GetString("MsgErrorPromptPlusConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleSchema has not been initialized..
        /// </summary>
        internal static string MsgErrorStyleSchema {
            get {
                return ResourceManager.GetString("MsgErrorStyleSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only selected.
        /// </summary>
        internal static string MultiFileOnlySelected {
            get {
                return ResourceManager.GetString("MultiFileOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting task.
        /// </summary>
        internal static string MultiFileRunningBackground {
            get {
                return ResourceManager.GetString("MultiFileRunningBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum item selection({0}) has been exceeded.
        /// </summary>
        internal static string MultiSelectMaxSelection {
            get {
                return ResourceManager.GetString("MultiSelectMaxSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum selection of {0} items is required.
        /// </summary>
        internal static string MultiSelectMinSelection {
            get {
                return ResourceManager.GetString("MultiSelectMinSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed.
        /// </summary>
        internal static string MultiTasksFailed {
            get {
                return ResourceManager.GetString("MultiTasksFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} ok.
        /// </summary>
        internal static string MultiTasksSuccessCount {
            get {
                return ResourceManager.GetString("MultiTasksSuccessCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} wait.
        /// </summary>
        internal static string MultiTasksWaitingCount {
            get {
                return ResourceManager.GetString("MultiTasksWaitingCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string NoChar {
            get {
                return ResourceManager.GetString("NoChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty:{0} items. {1} of {2} pages..
        /// </summary>
        internal static string PaginationTemplate {
            get {
                return ResourceManager.GetString("PaginationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected item does not meet the criteria.
        /// </summary>
        internal static string PredicateSelectInvalid {
            get {
                return ResourceManager.GetString("PredicateSelectInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key.
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Key.
        /// </summary>
        internal static string PressKey {
            get {
                return ResourceManager.GetString("PressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize the terminal ({0} height and {1} width). The current one is ({2} and {3})....
        /// </summary>
        internal static string ResizeTerminalWarning {
            get {
                return ResourceManager.GetString("ResizeTerminalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item disabled.
        /// </summary>
        internal static string SelectionDisabled {
            get {
                return ResourceManager.GetString("SelectionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing notes from day {0}.
        /// </summary>
        internal static string ShowingCalendarNotes {
            get {
                return ResourceManager.GetString("ShowingCalendarNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        internal static string TooltipBase {
            get {
                return ResourceManager.GetString("TooltipBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrows:Navigate.
        /// </summary>
        internal static string TooltipBaseNavegate {
            get {
                return ResourceManager.GetString("TooltipBaseNavegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:To cancel.
        /// </summary>
        internal static string TooltipCancelEsc {
            get {
                return ResourceManager.GetString("TooltipCancelEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Switch Layout.
        /// </summary>
        internal static string TooltipChartBarSwitchLayout {
            get {
                return ResourceManager.GetString("TooltipChartBarSwitchLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Show/Hide Legend.
        /// </summary>
        internal static string TooltipChartBarSwitchLegend {
            get {
                return ResourceManager.GetString("TooltipChartBarSwitchLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Change Order.
        /// </summary>
        internal static string TooltipChartBarSwitchOrder {
            get {
                return ResourceManager.GetString("TooltipChartBarSwitchOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chech/Uncheck all item.
        /// </summary>
        internal static string TooltipCheckAll {
            get {
                return ResourceManager.GetString("TooltipCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space:Check/Uncheck.
        /// </summary>
        internal static string TooltipCheckItem {
            get {
                return ResourceManager.GetString("TooltipCheckItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selected..
        /// </summary>
        internal static string TooltipCountCheck {
            get {
                return ResourceManager.GetString("TooltipCountCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter:Finish.
        /// </summary>
        internal static string TooltipEnterFinish {
            get {
                return ResourceManager.GetString("TooltipEnterFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter:Select item.
        /// </summary>
        internal static string TooltipEnterSelect {
            get {
                return ResourceManager.GetString("TooltipEnterSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +/-:Expand/Collapse.
        /// </summary>
        internal static string TooltipExpandCollapse {
            get {
                return ResourceManager.GetString("TooltipExpandCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a character to start the filter.
        /// </summary>
        internal static string TooltipFilter {
            get {
                return ResourceManager.GetString("TooltipFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show marked only.
        /// </summary>
        internal static string TooltipFilterAllSelected {
            get {
                return ResourceManager.GetString("TooltipFilterAllSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Del:Clear historic.
        /// </summary>
        internal static string TooltipHistoryClear {
            get {
                return ResourceManager.GetString("TooltipHistoryClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Historic(Min. {0} chars).
        /// </summary>
        internal static string TooltipHistoryShow {
            get {
                return ResourceManager.GetString("TooltipHistoryShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the initial character to jump to the item.
        /// </summary>
        internal static string TooltipJump {
            get {
                return ResourceManager.GetString("TooltipJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab\ShiftTab:Jumps between delimiters .
        /// </summary>
        internal static string TooltipJumpdelimiter {
            get {
                return ResourceManager.GetString("TooltipJumpdelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right/Start/End: Moves the cursor within the prompt.
        /// </summary>
        internal static string TooltipNavegateTextPrompt {
            get {
                return ResourceManager.GetString("TooltipNavegateTextPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up/Down/PgUp/PgDown: Move Selector, Ctrl+Home/End:First/Last item.
        /// </summary>
        internal static string TooltipPages {
            get {
                return ResourceManager.GetString("TooltipPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Space:Check/Uncheck recursively.
        /// </summary>
        internal static string TooltipRecursiveMark {
            get {
                return ResourceManager.GetString("TooltipRecursiveMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide tooltips.
        /// </summary>
        internal static string TooltipShowHide {
            get {
                return ResourceManager.GetString("TooltipShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right/Tab/ShiftTab:Changes value.
        /// </summary>
        internal static string TooltipSliderLeftRight {
            get {
                return ResourceManager.GetString("TooltipSliderLeftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up/Down/Tab/ShiftTab:Changes value.
        /// </summary>
        internal static string TooltipSliderUpDown {
            get {
                return ResourceManager.GetString("TooltipSliderUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftTab:Abort Sugestion.
        /// </summary>
        internal static string TooltipSuggestionShiftTab {
            get {
                return ResourceManager.GetString("TooltipSuggestionShiftTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab:Show Sugestion,again Accept (Min. {0} chars).
        /// </summary>
        internal static string TooltipSuggestionTab {
            get {
                return ResourceManager.GetString("TooltipSuggestionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab/ShiftTab:Suggestions (Min. {0} chars).
        /// </summary>
        internal static string TooltipSuggestionToggleAuto {
            get {
                return ResourceManager.GetString("TooltipSuggestionToggleAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right (or Space):Toggle.
        /// </summary>
        internal static string TooltipSwitch {
            get {
                return ResourceManager.GetString("TooltipSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab/ShiftTab:Navigate columns.
        /// </summary>
        internal static string TooltipTableColumnNav {
            get {
                return ResourceManager.GetString("TooltipTableColumnNav", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type initial char to jump (filterable columns).
        /// </summary>
        internal static string TooltipTableJump {
            get {
                return ResourceManager.GetString("TooltipTableJump", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}:Toggle tooltips.
        /// </summary>
        internal static string TooltipToggle {
            get {
                return ResourceManager.GetString("TooltipToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle full path/name.
        /// </summary>
        internal static string TooltipToggleFullPath {
            get {
                return ResourceManager.GetString("TooltipToggleFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Hide Notes.
        /// </summary>
        internal static string TooltipToggleNotes {
            get {
                return ResourceManager.GetString("TooltipToggleNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab:Next/Expand ShiftTab:Prev/Collapse.
        /// </summary>
        internal static string TooltipTreeTab {
            get {
                return ResourceManager.GetString("TooltipTreeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch view password.
        /// </summary>
        internal static string TooltipViewPassword {
            get {
                return ResourceManager.GetString("TooltipViewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string YesChar {
            get {
                return ResourceManager.GetString("YesChar", resourceCulture);
            }
        }
    }
}
