//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPlus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PromptPlusResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PromptPlusResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPlus.Resources.PromptPlusResources", typeof(PromptPlusResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added items.
        /// </summary>
        internal static string AddedItems {
            get {
                return ResourceManager.GetString("AddedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        internal static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key .
        /// </summary>
        internal static string AnyKey {
            get {
                return ResourceManager.GetString("AnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string CanceledKey {
            get {
                return ResourceManager.GetString("CanceledKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        internal static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current folder.
        /// </summary>
        internal static string CurrentFolder {
            get {
                return ResourceManager.GetString("CurrentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current seleted.
        /// </summary>
        internal static string CurrentSeleted {
            get {
                return ResourceManager.GetString("CurrentSeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit mode.
        /// </summary>
        internal static string EditMode {
            get {
                return ResourceManager.GetString("EditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter:Fisnish.
        /// </summary>
        internal static string InputFisnishEnter {
            get {
                return ResourceManager.GetString("InputFisnishEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mask.
        /// </summary>
        internal static string InvalidMask {
            get {
                return ResourceManager.GetString("InvalidMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exists.
        /// </summary>
        internal static string ListItemAlreadyexists {
            get {
                return ResourceManager.GetString("ListItemAlreadyexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum input of {0} items has already been reached.
        /// </summary>
        internal static string ListMaxSelection {
            get {
                return ResourceManager.GetString("ListMaxSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum input of {0} items is required.
        /// </summary>
        internal static string ListMinSelection {
            get {
                return ResourceManager.GetString("ListMinSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Del/Ctrl+L:Erase all, Home/End:Jump.
        /// </summary>
        internal static string MaskEditErase {
            get {
                return ResourceManager.GetString("MaskEditErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Next part .
        /// </summary>
        internal static string MaskEditJump {
            get {
                return ResourceManager.GetString("MaskEditJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any char.
        /// </summary>
        internal static string MaskEditPosAnyChar {
            get {
                return ResourceManager.GetString("MaskEditPosAnyChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only({0}).
        /// </summary>
        internal static string MaskEditPosCustom {
            get {
                return ResourceManager.GetString("MaskEditPosCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string MaskEditPosDay {
            get {
                return ResourceManager.GetString("MaskEditPosDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string MaskEditPosHour {
            get {
                return ResourceManager.GetString("MaskEditPosHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        internal static string MaskEditPosLetter {
            get {
                return ResourceManager.GetString("MaskEditPosLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string MaskEditPosMinute {
            get {
                return ResourceManager.GetString("MaskEditPosMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string MaskEditPosMonth {
            get {
                return ResourceManager.GetString("MaskEditPosMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string MaskEditPosNumeric {
            get {
                return ResourceManager.GetString("MaskEditPosNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string MaskEditPosSecond {
            get {
                return ResourceManager.GetString("MaskEditPosSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string MaskEditPosYear {
            get {
                return ResourceManager.GetString("MaskEditPosYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter:Fisnish, Space:Check/Uncheck.
        /// </summary>
        internal static string MultiSelectFisnishEnter {
            get {
                return ResourceManager.GetString("MultiSelectFisnishEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum item selection({0}) has been exceeded.
        /// </summary>
        internal static string MultiSelectMaxSelection {
            get {
                return ResourceManager.GetString("MultiSelectMaxSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum selection of {0} items is required.
        /// </summary>
        internal static string MultiSelectMinSelection {
            get {
                return ResourceManager.GetString("MultiSelectMinSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string NoChar {
            get {
                return ResourceManager.GetString("NoChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OffValue {
            get {
                return ResourceManager.GetString("OffValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string OnValue {
            get {
                return ResourceManager.GetString("OnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items, {1}/{2} pages.
        /// </summary>
        internal static string PaginationTemplate {
            get {
                return ResourceManager.GetString("PaginationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home:Fist Page.
        /// </summary>
        internal static string PaginatorHome {
            get {
                return ResourceManager.GetString("PaginatorHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressed key.
        /// </summary>
        internal static string PressedKey {
            get {
                return ResourceManager.GetString("PressedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter:Fisnish.
        /// </summary>
        internal static string SelectFisnishEnter {
            get {
                return ResourceManager.GetString("SelectFisnishEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item disabled.
        /// </summary>
        internal static string SelectionDisabled {
            get {
                return ResourceManager.GetString("SelectionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Invalid.
        /// </summary>
        internal static string SelectionInvalid {
            get {
                return ResourceManager.GetString("SelectionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right:Short change, Tab/Shift+Tab:Larger change, Enter:Finish.
        /// </summary>
        internal static string SliderNumberLeftRightKeyNavigator {
            get {
                return ResourceManager.GetString("SliderNumberLeftRightKeyNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up/Down:Short change, Tab/Shift+Tab:Larger change, Enter:Finish.
        /// </summary>
        internal static string SliderNumberUpDownKeyNavigator {
            get {
                return ResourceManager.GetString("SliderNumberUpDownKeyNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right:Change, Enter:Finish.
        /// </summary>
        internal static string SliderSwitchKeyNavigator {
            get {
                return ResourceManager.GetString("SliderSwitchKeyNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc:Cancel Edit.
        /// </summary>
        internal static string TooltipAbortEdit {
            get {
                return ResourceManager.GetString("TooltipAbortEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:To cancel.
        /// </summary>
        internal static string TooltipCancelEsc {
            get {
                return ResourceManager.GetString("TooltipCancelEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up/Down/PgUp/PgDown:Move, Esc:End chart navigation.
        /// </summary>
        internal static string TooltipChart {
            get {
                return ResourceManager.GetString("TooltipChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Edit item.
        /// </summary>
        internal static string TooltipEditItem {
            get {
                return ResourceManager.GetString("TooltipEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter:Add, Ctrl+Enter:Fisnish.
        /// </summary>
        internal static string TooltipEnterPressList {
            get {
                return ResourceManager.GetString("TooltipEnterPressList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Toggle Full Path.
        /// </summary>
        internal static string TooltipFullPath {
            get {
                return ResourceManager.GetString("TooltipFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Del:Clear historic.
        /// </summary>
        internal static string TooltipHistoryClear {
            get {
                return ResourceManager.GetString("TooltipHistoryClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc:Cancel historic.
        /// </summary>
        internal static string TooltipHistoryEsc {
            get {
                return ResourceManager.GetString("TooltipHistoryEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down/PgDown:Historic(Min. {0} chars).
        /// </summary>
        internal static string TooltipHistoryToggle {
            get {
                return ResourceManager.GetString("TooltipHistoryToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Invert Seleted.
        /// </summary>
        internal static string TooltipInvertSelectAll {
            get {
                return ResourceManager.GetString("TooltipInvertSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up/Down/PgUp/PgDown:Move Selector.
        /// </summary>
        internal static string TooltipPages {
            get {
                return ResourceManager.GetString("TooltipPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Space:Space.
        /// </summary>
        internal static string TooltipPressSpace {
            get {
                return ResourceManager.GetString("TooltipPressSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Remove item.
        /// </summary>
        internal static string TooltipRemoveItem {
            get {
                return ResourceManager.GetString("TooltipRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Select All.
        /// </summary>
        internal static string TooltipSelectAll {
            get {
                return ResourceManager.GetString("TooltipSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:Enter text to filter the items.
        /// </summary>
        internal static string TooltipSelectFilter {
            get {
                return ResourceManager.GetString("TooltipSelectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc:Cancel sugestion.
        /// </summary>
        internal static string TooltipSugestionEsc {
            get {
                return ResourceManager.GetString("TooltipSugestionEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab/Shift Tab:Sugestions.
        /// </summary>
        internal static string TooltipSugestionToggle {
            get {
                return ResourceManager.GetString("TooltipSugestionToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Toggle tooltips.
        /// </summary>
        internal static string TooltipToggle {
            get {
                return ResourceManager.GetString("TooltipToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Expand/Collapse All.
        /// </summary>
        internal static string TooltipToggleExpandAllPress {
            get {
                return ResourceManager.GetString("TooltipToggleExpandAllPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Expand/Collapse.
        /// </summary>
        internal static string TooltipToggleExpandPress {
            get {
                return ResourceManager.GetString("TooltipToggleExpandPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:Swith view password.
        /// </summary>
        internal static string TooltipViewPassword {
            get {
                return ResourceManager.GetString("TooltipViewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a valid key.
        /// </summary>
        internal static string ValidAnyKey {
            get {
                return ResourceManager.GetString("ValidAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value!.
        /// </summary>
        internal static string ValidateInvalid {
            get {
                return ResourceManager.GetString("ValidateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too long. Max({0}).
        /// </summary>
        internal static string ValidateMaxLength {
            get {
                return ResourceManager.GetString("ValidateMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too short. Min({0}).
        /// </summary>
        internal static string ValidateMinLength {
            get {
                return ResourceManager.GetString("ValidateMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not match pattern.
        /// </summary>
        internal static string ValidateNoMatchRegex {
            get {
                return ResourceManager.GetString("ValidateNoMatchRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Value!.
        /// </summary>
        internal static string ValidateRequired {
            get {
                return ResourceManager.GetString("ValidateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid keys.
        /// </summary>
        internal static string Validkeys {
            get {
                return ResourceManager.GetString("Validkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait.
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string YesChar {
            get {
                return ResourceManager.GetString("YesChar", resourceCulture);
            }
        }
    }
}
