// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.MultiTasksControlTests.Mid_run_shows_running_and_waiting_tasks_with_their_own_glyphs")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.MultiFileControlRealFilesystemTests.Checking_a_folder_recursively_walks_the_real_disk_subtree_in_the_background")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.MultiFileControlTests.Re_pressing_the_check_key_on_a_running_background_op_cancels_it")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.MultiFileControlTests.RecursiveMarkWithCtrlSpace_moves_the_recursive_action_to_ctrl_space")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.MultiFileControlTests.Space_on_a_fully_checked_folder_unchecks_the_subtree_synchronously")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.MultiFileControlTests.Space_on_an_unchecked_folder_recursively_checks_the_subtree_in_the_background")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.MultiTasksControlTests.Escape_aborts_and_captures_a_snapshot_of_current_task_states")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.MultiTasksControlTests.F1_cycles_through_navigation_abort_and_showhide_tooltips")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.MultiTasksControlTests.PageSize_limits_the_visible_task_rows_per_page")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.MultiTasksControlTests.Parallel_mode_runs_consecutive_tasks_concurrently")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ProgressBarControlTests.ChangeDescription_reflects_the_current_value")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ProgressBarControlTests.ChangeDescriptionAsync_is_awaited_and_reflects_the_current_value")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ProgressBarControlTests.F1_cycles_the_tooltip_to_the_next_hint")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ProgressBarControlTests.Gradient_colors_the_filled_columns_differently_across_the_bar")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ProgressBarControlTests.HideElements_ElapsedTime_is_honored_on_both_the_running_and_final_frame")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ProgressBarControlTests.Mid_progress_can_be_observed_deterministically_via_a_real_handshake")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ProgressBarControlTests.Re_pressing_escape_cancels_a_running_operation_before_completion")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ResizeRelayoutTests.A_within_bounds_resize_does_not_leave_duplicated_or_stale_content_on_screen")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ResizeRelayoutTests.A_within_bounds_resize_preserves_a_scrolled_answer_preview_on_Select")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ResizeRelayoutTests.A_within_bounds_resize_preserves_a_scrolled_answer_preview_on_Tree")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ResizeRelayoutTests.A_within_bounds_resize_preserves_a_scrolled_answer_preview_on_MultiTree")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ResizeRelayoutTests.A_within_bounds_resize_preserves_a_scrolled_answer_preview_on_File")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ResizeRelayoutTests.A_within_bounds_resize_preserves_a_scrolled_answer_preview_on_MultiFile")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.ResizeRelayoutTests.A_within_bounds_resize_preserves_the_in_progress_edit_cursor_position")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.TaskControlTests.ChangeDescription_and_ChangeDescriptionAsync_reflect_state_while_running")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.TaskControlTests.ChangeDescriptionAsync_is_awaited_while_running")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.TaskControlTests.Default_render_keeps_the_tooltip_on_its_own_row_while_running")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.TaskControlTests.F1_cycles_the_tooltip_to_the_next_hint")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.TaskControlTests.ShowElapsedTime_and_spinner_are_observable_while_running_on_the_same_row")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.TimeControlTests.F1_cycles_from_the_abort_tooltip_to_the_showhide_tooltip")]
[assembly: SuppressMessage("Usage", "xUnit1031:Do not use blocking task operations in test method", Justification = "ByDesign", Scope = "member", Target = "~M:PromptPlus.Tests.Controls.TimeControlTests.Spinner_and_ChangeDescription_are_observable_while_still_counting_down")]
