//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPlus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PromptPlusResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PromptPlusResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPlus.Resources.PromptPlusResources", typeof(PromptPlusResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key.
        /// </summary>
        internal static string AnyKey {
            get {
                return ResourceManager.GetString("AnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter: Select, {0}: Unselect, Ctrl-Enter: Update text input.
        /// </summary>
        internal static string AutoCompleteKeyNavigation {
            get {
                return ResourceManager.GetString("AutoCompleteKeyNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found in sugestions.
        /// </summary>
        internal static string AutoCompleteKeyNotfound {
            get {
                return ResourceManager.GetString("AutoCompleteKeyNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string CanceledText {
            get {
                return ResourceManager.GetString("CanceledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Title.
        /// </summary>
        internal static string EmptyTitle {
            get {
                return ResourceManager.GetString("EmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter: Finish.
        /// </summary>
        internal static string EnterFininsh {
            get {
                return ResourceManager.GetString("EnterFininsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0}: To cancel.
        /// </summary>
        internal static string EscCancel {
            get {
                return ResourceManager.GetString("EscCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0}: Cancel pipe, {1}: Cancel all pipes.
        /// </summary>
        internal static string EscCancelWithPipeline {
            get {
                return ResourceManager.GetString("EscCancelWithPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0}: Cancel pipe.
        /// </summary>
        internal static string EscCancelWithPipeNotAll {
            get {
                return ResourceManager.GetString("EscCancelWithPipeNotAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item not a file!.
        /// </summary>
        internal static string FileNotSelected {
            get {
                return ResourceManager.GetString("FileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish with {0} items.
        /// </summary>
        internal static string FinishResultList {
            get {
                return ResourceManager.GetString("FinishResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish all tasks({0}).
        /// </summary>
        internal static string FinishResultTasks {
            get {
                return ResourceManager.GetString("FinishResultTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        internal static string FolderCurrentPath {
            get {
                return ResourceManager.GetString("FolderCurrentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Left/Right: Dry folder, Enter: Select, {0}: Filter.
        /// </summary>
        internal static string FolderKeyNavigation {
            get {
                return ResourceManager.GetString("FolderKeyNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Show/Hide description.
        /// </summary>
        internal static string HotKeyDescription {
            get {
                return ResourceManager.GetString("HotKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is invalid.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for number boolean(0:False/1:True).
        /// </summary>
        internal static string InvalidTypeBoolean {
            get {
                return ResourceManager.GetString("InvalidTypeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for number (-128 to 127).
        /// </summary>
        internal static string InvalidTypeByte {
            get {
                return ResourceManager.GetString("InvalidTypeByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for single character.
        /// </summary>
        internal static string InvalidTypeChar {
            get {
                return ResourceManager.GetString("InvalidTypeChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for Date({0})/Time({1}).
        /// </summary>
        internal static string InvalidTypeDateTime {
            get {
                return ResourceManager.GetString("InvalidTypeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for number.
        /// </summary>
        internal static string InvalidTypeNumber {
            get {
                return ResourceManager.GetString("InvalidTypeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Filtered!.
        /// </summary>
        internal static string ItemsFiltered {
            get {
                return ResourceManager.GetString("ItemsFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PgUp/PgDown: Page, .
        /// </summary>
        internal static string KeyNavPaging {
            get {
                return ResourceManager.GetString("KeyNavPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exists.
        /// </summary>
        internal static string ListItemAlreadyexists {
            get {
                return ResourceManager.GetString("ListItemAlreadyexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Del: Remove seleted , {0}: Remove all, Enter: Finish.
        /// </summary>
        internal static string ListKeyNavigation {
            get {
                return ResourceManager.GetString("ListKeyNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum input of {0} items has already been reached.
        /// </summary>
        internal static string ListMaxSelection {
            get {
                return ResourceManager.GetString("ListMaxSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum input of {0} items is required.
        /// </summary>
        internal static string ListMinSelection {
            get {
                return ResourceManager.GetString("ListMinSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string LongNoKey {
            get {
                return ResourceManager.GetString("LongNoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string LongYesKey {
            get {
                return ResourceManager.GetString("LongYesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,Ctrl+Del: Erase all.
        /// </summary>
        internal static string MaskEditErase {
            get {
                return ResourceManager.GetString("MaskEditErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input type: {0}.
        /// </summary>
        internal static string MaskEditInputType {
            get {
                return ResourceManager.GetString("MaskEditInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any char.
        /// </summary>
        internal static string MaskEditPosAnyChar {
            get {
                return ResourceManager.GetString("MaskEditPosAnyChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only({0}).
        /// </summary>
        internal static string MaskEditPosCustom {
            get {
                return ResourceManager.GetString("MaskEditPosCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string MaskEditPosDay {
            get {
                return ResourceManager.GetString("MaskEditPosDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string MaskEditPosHour {
            get {
                return ResourceManager.GetString("MaskEditPosHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        internal static string MaskEditPosLetter {
            get {
                return ResourceManager.GetString("MaskEditPosLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string MaskEditPosMinute {
            get {
                return ResourceManager.GetString("MaskEditPosMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string MaskEditPosMonth {
            get {
                return ResourceManager.GetString("MaskEditPosMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string MaskEditPosNumeric {
            get {
                return ResourceManager.GetString("MaskEditPosNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string MaskEditPosSecond {
            get {
                return ResourceManager.GetString("MaskEditPosSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string MaskEditPosYear {
            get {
                return ResourceManager.GetString("MaskEditPosYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too long. Max({0}).
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too short. Min({0}).
        /// </summary>
        internal static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space: Select, Enter: Finish, {0}: Filter, {1}: All, {2}:Invert.
        /// </summary>
        internal static string MultiSelectKeyNavigation {
            get {
                return ResourceManager.GetString("MultiSelectKeyNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum selection of {0} items has already been reached.
        /// </summary>
        internal static string MultiSelectMaxSelection {
            get {
                return ResourceManager.GetString("MultiSelectMaxSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum selection of {0} items is required.
        /// </summary>
        internal static string MultiSelectMinSelection {
            get {
                return ResourceManager.GetString("MultiSelectMinSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string NoKey {
            get {
                return ResourceManager.GetString("NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not match pattern.
        /// </summary>
        internal static string NoMatchRegex {
            get {
                return ResourceManager.GetString("NoMatchRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up/Down: Short change, Crtl+Left/Right: Larger change, Enter: Finish.
        /// </summary>
        internal static string NumberUpDownKeyNavigator {
            get {
                return ResourceManager.GetString("NumberUpDownKeyNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OffValue {
            get {
                return ResourceManager.GetString("OffValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string OnValue {
            get {
                return ResourceManager.GetString("OnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0} items, {1}/{2} pages.
        /// </summary>
        internal static string PaginationTemplate {
            get {
                return ResourceManager.GetString("PaginationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}:Show/Hide password.
        /// </summary>
        internal static string PasswordStandardHotkeys {
            get {
                return ResourceManager.GetString("PasswordStandardHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipes summary.
        /// </summary>
        internal static string PipeLineText {
            get {
                return ResourceManager.GetString("PipeLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressed key.
        /// </summary>
        internal static string PressedKey {
            get {
                return ResourceManager.GetString("PressedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal has resized!.
        /// </summary>
        internal static string ResizedTerminal {
            get {
                return ResourceManager.GetString("ResizedTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize : {0} to {1} rows...Press any key..
        /// </summary>
        internal static string ResizeTerminal {
            get {
                return ResourceManager.GetString("ResizeTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string RunningText {
            get {
                return ResourceManager.GetString("RunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter: Select, {0}: Filter.
        /// </summary>
        internal static string SelectKeyNavigation {
            get {
                return ResourceManager.GetString("SelectKeyNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        internal static string ShowKeyPressStandardHotKeys {
            get {
                return ResourceManager.GetString("ShowKeyPressStandardHotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} Swith pipes summary{2}.
        /// </summary>
        internal static string ShowKeyPressStandardHotKeysWithPipeline {
            get {
                return ResourceManager.GetString("ShowKeyPressStandardHotKeysWithPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Swith pipes summary{1}.
        /// </summary>
        internal static string ShowProcessStandardHotKeysWithPipeline {
            get {
                return ResourceManager.GetString("ShowProcessStandardHotKeysWithPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} Show/Hide description, {2} Swith pipes summary.
        /// </summary>
        internal static string ShowProcessStandardHotKeysWithPipelineDesc {
            get {
                return ResourceManager.GetString("ShowProcessStandardHotKeysWithPipelineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Show/Hide tooltips{1}.
        /// </summary>
        internal static string ShowStandardHotKeys {
            get {
                return ResourceManager.GetString("ShowStandardHotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Show/Hide tooltips, {1} Show/Hide description{2}.
        /// </summary>
        internal static string ShowStandardHotKeysDesc {
            get {
                return ResourceManager.GetString("ShowStandardHotKeysDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Show/Hide keys, {1} Swith pipes summary{2}.
        /// </summary>
        internal static string ShowStandardHotKeysWithPipeline {
            get {
                return ResourceManager.GetString("ShowStandardHotKeysWithPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Show/Hide keys, {1} Show/Hide description, {2} Swith pipes summary{3}.
        /// </summary>
        internal static string ShowStandardHotKeysWithPipelineDesc {
            get {
                return ResourceManager.GetString("ShowStandardHotKeysWithPipelineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiped.
        /// </summary>
        internal static string SkipedText {
            get {
                return ResourceManager.GetString("SkipedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left/Right: Short change, Crtl+Left/Right: Larger change, Enter: Finish.
        /// </summary>
        internal static string SliderNumberKeyNavigator {
            get {
                return ResourceManager.GetString("SliderNumberKeyNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Left/Right: Change, Enter: Finish.
        /// </summary>
        internal static string SliderSwitcheKeyNavigator {
            get {
                return ResourceManager.GetString("SliderSwitcheKeyNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return to.
        /// </summary>
        internal static string SummaryPipelineReturnto {
            get {
                return ResourceManager.GetString("SummaryPipelineReturnto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0} of {1}.
        /// </summary>
        internal static string WaittingProcess {
            get {
                return ResourceManager.GetString("WaittingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string WaittingText {
            get {
                return ResourceManager.GetString("WaittingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string YesKey {
            get {
                return ResourceManager.GetString("YesKey", resourceCulture);
            }
        }
    }
}
