// ***************************************************************************************
// MIT LICENCE
// The maintenance and evolution is maintained by the PromptPlus project under MIT license
// ***************************************************************************************

namespace PPlus.Controls
{
    internal enum SymbolType
    {
        MaskEmpty,
        Done,
        Selector,
        Selected,
        NotSelect,
        Expanded,
        Collapsed,
        IndentGroup,
        IndentEndGroup,
        TreeLinecross,
        TreeLinecorner,
        TreeLinevertical,
        TreeLinespace,
        DoubleBorder,
        SingleBorder,
        HeavyBorder,
        TaskSingle,
        TaskFist,
        TaskMiddle,
        ProgressBarLight,
        ProgressBarDoubleLight,
        ProgressBarHeavy,
        ProgressBarSquare,
        ProgressBarBar,
        ProgressBarAsciiSingle,
        ProgressBarAsciiDouble,
        ProgressBarDot,
        SliderBarLight,
        SliderBarDoubleLight,
        SliderBarHeavy,
        SliderBarSquare,
        ChartLabel,
        ChartLight,
        ChartHeavy,
        ChartSquare,
        GridSingleTopLeft,
        GridSingleTopCenter,
        GridSingleTopRight,
        GridSingleMiddleLeft,
        GridSingleMiddleCenter,
        GridSingleMiddleRight,
        GridSingleBottomLeft,
        GridSingleBottomCenter,
        GridSingleBottomRight,
        GridSingleBorderLeft,
        GridSingleBorderRight,
        GridSingleBorderTop,
        GridSingleBorderBottom,
        GridSingleDividerY,
        GridSingleDividerX,
        GridDoubleTopLeft,
        GridDoubleTopCenter,
        GridDoubleTopRight,
        GridDoubleMiddleLeft,
        GridDoubleMiddleCenter,
        GridDoubleMiddleRight,
        GridDoubleBottomLeft,
        GridDoubleBottomCenter,
        GridDoubleBottomRight,
        GridDoubleBorderLeft,
        GridDoubleBorderRight,
        GridDoubleBorderTop,
        GridDoubleBorderBottom,
        GridDoubleDividerY,
        GridDoubleDividerX
    }
}
