//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPlus.CommandDotNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPlus.CommandDotNet.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There AllowsMany for {0} with PromptPlus Type Browser..
        /// </summary>
        internal static string Ex_PromptTypeBrowser {
            get {
                return ResourceManager.GetString("Ex_PromptTypeBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is AllowedValues or type is Password or type is bool for {0}. .
        /// </summary>
        internal static string Ex_PromptTypeError {
            get {
                return ResourceManager.GetString("Ex_PromptTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PromptTypeKind {0} for {1}..
        /// </summary>
        internal static string Ex_PromptTypeKind {
            get {
                return ResourceManager.GetString("Ex_PromptTypeKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is more than one PromptType attribute record for {0].
        /// </summary>
        internal static string Ex_PromptTypeMany {
            get {
                return ResourceManager.GetString("Ex_PromptTypeMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must register {0} to ensure an {1} is available..
        /// </summary>
        internal static string Ex_RegisterConsole {
            get {
                return ResourceManager.GetString("Ex_RegisterConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long name or short name must be filled.
        /// </summary>
        internal static string Ex_ReplControlOptions {
            get {
                return ResourceManager.GetString("Ex_ReplControlOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propery WizardControl is empty.
        /// </summary>
        internal static string Ex_WizardControl {
            get {
                return ResourceManager.GetString("Ex_WizardControl", resourceCulture);
            }
        }
    }
}
