//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPlus.CommandDotNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPlus.CommandDotNet.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has been cleared all history items..
        /// </summary>
        internal static string Repl_clear_history {
            get {
                return ResourceManager.GetString("Repl_clear_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interative session.
        /// </summary>
        internal static string Repl_default_description {
            get {
                return ResourceManager.GetString("Repl_default_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit interative session.
        /// </summary>
        internal static string Repl_exit {
            get {
                return ResourceManager.GetString("Repl_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update history.
        /// </summary>
        internal static string Repl_history_description {
            get {
                return ResourceManager.GetString("Repl_history_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: value default = {0} days, value 0 clear history..
        /// </summary>
        internal static string Repl_history_note {
            get {
                return ResourceManager.GetString("Repl_history_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;replhistory &lt;days&gt;,&lt;hours&gt;,&lt;minutes&gt;&apos; to update history..
        /// </summary>
        internal static string Repl_history_update {
            get {
                return ResourceManager.GetString("Repl_history_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Type &apos;quit&apos; to exit..
        /// </summary>
        internal static string Repl_init_session {
            get {
                return ResourceManager.GetString("Repl_init_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid values for Updated History.
        /// </summary>
        internal static string Repl_invalid_values_history {
            get {
                return ResourceManager.GetString("Repl_invalid_values_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated History to {0} days, {1} hours and {2} minutes..
        /// </summary>
        internal static string Repl_Ok_history {
            get {
                return ResourceManager.GetString("Repl_Ok_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command for {0}: {1}.
        /// </summary>
        internal static string WizardCommandFor {
            get {
                return ResourceManager.GetString("WizardCommandFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directive for wizard prompt:%\n%%\n%   [{0}] to wizard find commands, options and arguments with prompt and execute!!! (Remark: Shouldn&apos;t have any more arguments), eg.: %AppName% [{0}]..
        /// </summary>
        internal static string WizardHelpText {
            get {
                return ResourceManager.GetString("WizardHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Enter: Next, {0}: Run, {1}: Back command.
        /// </summary>
        internal static string WizardKeyNavigation {
            get {
                return ResourceManager.GetString("WizardKeyNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Enter: Next, {0}: Run.
        /// </summary>
        internal static string WizardKeyNavigationNoBack {
            get {
                return ResourceManager.GetString("WizardKeyNavigationNoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Argument(s).
        /// </summary>
        internal static string WizardMissingOperands {
            get {
                return ResourceManager.GetString("WizardMissingOperands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string WizardNext {
            get {
                return ResourceManager.GetString("WizardNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no description.
        /// </summary>
        internal static string WizardNoDescription {
            get {
                return ResourceManager.GetString("WizardNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument for {0}: {1}.
        /// </summary>
        internal static string WizardOperandFor {
            get {
                return ResourceManager.GetString("WizardOperandFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option for {0}: {1}.
        /// </summary>
        internal static string WizardOptionFor {
            get {
                return ResourceManager.GetString("WizardOptionFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type({0}).
        /// </summary>
        internal static string WizardTypeInfo {
            get {
                return ResourceManager.GetString("WizardTypeInfo", resourceCulture);
            }
        }
    }
}
