name: Publish

on:
  push:
    branches: [ IntegrationCommandLine ]
    tags:
      - PromptPlus*"
      - PPlusCmdDotNet*"

env:
  DOTNET_VERSION: 6.0.x

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install .NET Core format tool
      run: dotnet tool update -g dotnet-format      

    - name: Build projects
      run: dotnet build  PromptPlus.sln -c Release

    - name: Run test cases
      run: dotnet test -c Release --no-build      

    - name: Extract package , versionpkg and versioncmd
    - uses: olegtarasov/get-tag@v2.1
      id: tagName
      with:
        tagRegex: "(?<package>.*):(?<versionpkg>.*):(?<versioncmd>.*)" 

    - name: Pack NuGet Package pplus
      if: ${{ steps.tagName.outputs.package == 'PromptPlus'}}
      run: dotnet pack PromptPlus/PromptPlus.csproj -c Release -o ./dist -p:Version=${{ steps.tagName.outputs.versionpkg }}

    - name: Pack NuGet Package cmddotnet
      if: ${{ steps.tagName.outputs.package == 'PromptPlus' } || steps.tagName.outputs.package == 'PPlusCmdDotNet'}}
      run: dotnet pack PromptPlus.CommandDotNet/PromptPlus.CommandDotNet.csproj -c Release -o ./dist -p:Version=${{ steps.tagName.outputs.versioncmd }}

    - name: Publish pplus/cmddotnet
      run: dotnet nuget push dist/*.nupkg -k ${{ secrets.NUGET_API_KEYxxx }} -s https://api.nuget.org/v3/index.json
